### ISSUE TITLE
rules_js 2.0 coming soon...

### ISSUE THREAD

**Issue by gregmagolan** [fremtind/rules_vitest#14]
Hey @hjellek, just noticed this new rule set from the BCR PR this morning. Its great to see the community building out support for more node tools on top of rules_js.

Just a heads up that we're currently working on releasing rules_js 2.0 which has breaking changes to the internal API that rules_jest is using. Here is what the change looks like in rules_jest: https://github.com/aspect-build/rules_jest/pull/269.

Here is a tracking issue for the release work: https://github.com/aspect-build/rules_js/issues/1671. We're probably a few weeks away from releasing with a few more things we'd like to get in.

In any case, just wanted to give you a heads up incase you wanted to wait until we have a rules_js 2.0 release out before you launch rules_vitest.

**Comment by hjellek** [comment]
Hi @gregmagolan, thanks for reaching out and thanks for all your work.

I noticed that the pre-submit actions in BCR failed with an error anyway, so it sounds like a good idea to wait for rules_js 2.0.

Thanks for the heads up, I will submit a new PR once we have upgraded to rules_js 2.0.

**Comment by alexeagle** [comment]
Note, the first Release Candidate of rules_js 2.0 is now published :)
